api/urls.py
from django.contrib import admin
from django.urls import path
from ninja import NinjaAPI

from questions.api.api_v1 import router as questions_router
from users.api.api_v1 import router as users_router

from ninja import NinjaAPI

# app_name = 'api'

api_v1 = NinjaAPI(version='1.0.0', urls_namespace='api_v1')


# @api.get('/hello')
# def hello(request):
#     return {'message': 'Hello from V1'}
#
#
# @api.get("/add")
# def add(request, a: int, b: int):
#     return {"result": a + b}


api_v1.add_router("/questions/", questions_router)
api_v1.add_router("/users/", users_router)
# Exam

urlpatterns = [
    path('v1/', api_v1.urls, name='api_v1'),
]

questions/urls.py
from django.urls import path
from . import views


app_name = 'questions'
urlpatterns = [
    path('question-set/first-question/', views.question_set_first_question_view, name='set-first-question'),

    path('question-set/college-board-question-bank/', views.CollegeBoardQuestionBankCategoryListView.as_view(), name='question-set-cbqb'),
    path('question-set/princeton-review-practice-tests-question-bank/', views.PrincetonReviewPracticeTestsQuestionBankCategoryListView.as_view(), name='question-set-prptqb'),
    path('question-set/<str:question_set>/', views.QuestionSetView.as_view(), name='question-set'),
    # first question
    # path('questions/', views.QuestionListView.as_view(), name='question_list'),
    #
    path('question/<int:pk>/', views.QuestionDetailView.as_view(), name='detail'),
]

templates/basic/pages/questions/set/includes/category.html
{% load core_tags %}

{#<div class="my-4">#}
    <li class="w-full relative">
    <a class="" style="" {% if category.primary_class_count > 0 %}href="{% url 'questions:set-first-question' %}?{{ category.primary_class_args }}"{% endif %}>
{#        <span class="">{{ category.primary_class_count }}</span>#}
        <span class="badge badge-lg badge-secondary">{{ category.primary_class_count }}</span>
{#        <span class="">{{ terms|get_item:category.primary_class }}</span>#}
        <span class="">{% firstof terms|get_item:category.primary_class category.primary_class %}</span>
        {% if user.is_authenticated and category.primary_class_marked_count > 0 %}
            <span class="badge badge-lg badge-ghost badge-outline">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="inline-block h-4 w-4 mr-1 text-warning"><path fillRule="evenodd" d="M6.32 2.577a49.255 49.255 0 0 1 11.36 0c1.497.174 2.57 1.46 2.57 2.93V21a.75.75 0 0 1-1.085.67L12 18.089l-7.165 3.583A.75.75 0 0 1 3.75 21V5.507c0-1.47 1.073-2.756 2.57-2.93Z" clipRule="evenodd" /></svg>
                {{ category.primary_class_marked_count }}
            </span>
        {% endif %}
    </a>
        <ul>
            {% for subcategory in categories  %}
                {% if subcategory.primary_class == category.primary_class %}
                    <li class="w-full relative">
                        <a class="" style="" {% if subcategory.skill_count > 0 %}href="{% url 'questions:set-first-question' %}?{{ subcategory.skill_args }}"{% endif %}>
                            <span class="badge badge-lg badge-accent">{{ subcategory.skill_count }}</span>
                            <span class="">{% firstof terms|get_item:subcategory.skill subcategory.skill %}</span>
                            {% if user.is_authenticated and subcategory.skill_marked_count > 0 %}
                                <span class="badge badge-lg badge-ghost badge-outline">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="inline-block h-4 w-4 mr-1 text-warning"><path fillRule="evenodd" d="M6.32 2.577a49.255 49.255 0 0 1 11.36 0c1.497.174 2.57 1.46 2.57 2.93V21a.75.75 0 0 1-1.085.67L12 18.089l-7.165 3.583A.75.75 0 0 1 3.75 21V5.507c0-1.47 1.073-2.756 2.57-2.93Z" clipRule="evenodd" /></svg>
                                    {{ subcategory.skill_marked_count }}
                                </span>
                            {% endif %}
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </li>
{#</div>#}