api/urls.py
from django.contrib import admin
from django.urls import path
from ninja import NinjaAPI

from questions.api.api_v1 import router as questions_router
from users.api.api_v1 import router as users_router

from ninja import NinjaAPI

# app_name = 'api'

api_v1 = NinjaAPI(version='1.0.0', urls_namespace='api_v1')


# @api.get('/hello')
# def hello(request):
#     return {'message': 'Hello from V1'}
#
#
# @api.get("/add")
# def add(request, a: int, b: int):
#     return {"result": a + b}


api_v1.add_router("/questions/", questions_router)
api_v1.add_router("/users/", users_router)
# Exam

urlpatterns = [
    path('v1/', api_v1.urls, name='api_v1'),
]

charts/urls.py
from django.urls import path

from . import views

app_name = 'charts'

urlpatterns = [
    # path("user/<int:user_id>/charts/", views.chart_view, name="chart_with_user_id"),
    path("user/<str:username>/charts/", views.chart_view, name="chart_with_username"),
    path("user/charts/", views.chart_view, name="chart"),

    path('charts/admin/', views.admin_chart_view, name="admin_chart"),


    # path("charts/user/<int:user_id>/exam/<int:exam_id>/basic-time", views.basic_exam_time_view),
    path("charts/user/<str:username>/exam/<int:exam_id>/basic-time", views.basic_exam_time_view),
    path("charts/user/exam/<int:exam_id>/basic-time", views.basic_exam_time_view, name="basic_exam_time"),


]

questions/urls.py
from django.urls import path
from . import views


app_name = 'questions'
urlpatterns = [
    path('question-set/first-question/', views.question_set_first_question_view, name='set-first-question'),

    path('question-set/college-board-question-bank/', views.CollegeBoardQuestionBankCategoryListView.as_view(), name='question-set-cbqb'),
    path('question-set/princeton-review-practice-tests-question-bank/', views.PrincetonReviewPracticeTestsQuestionBankCategoryListView.as_view(), name='question-set-prptqb'),
    path('question-set/<str:question_set>/', views.QuestionSetView.as_view(), name='question-set'),
    # first question
    # path('questions/', views.QuestionListView.as_view(), name='question_list'),
    #
    path('question/<int:pk>/', views.QuestionDetailView.as_view(), name='detail'),
]

charts/models.py
from django.db import models

# Create your models here.

charts/views.py
from collections import defaultdict, OrderedDict
from datetime import timedelta
from typing import Optional, List

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Prefetch, Count
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from exams.models import Exam, ExamQuestion
from questions.models import Question, UserQuestionAnswer, UserQuestionStatus, Module
from users.models import User

from utils.datetime import get_date_range, get_date_format


@login_required
def chart_view(request, user_id=None, username=None):
    user: Optional[User] = None
    if not user_id and not username:
        user = request.user
    else:
        if user_id:
            user = get_object_or_404(User, id=user_id)
        elif username:
            user = get_object_or_404(User, username=username)

    if not user:
        raise Http404

    # dynamic past 30 days
    DAYS = 30
    try:
        DAYS = int(request.GET.get('days'))
    except:
        pass
    DAYS = min(DAYS, 90)
    MAX_TIME_GIVEN_LIMIT = 60 * 30  # 30 minutes
    try:
        MAX_TIME_GIVEN_LIMIT = int(request.GET.get('max_time_given_limit'))
    except:
        pass

    date__gte = (timezone.now() - timezone.timedelta(days=DAYS)).date()

    # Attempts Chart
    answer_set = user \
        .question_answer_set \
        .order_by('answered_at') \
        .filter(answered_at__date__gt=date__gte) \
        .prefetch_related(
            Prefetch('question', queryset=Question.objects.only('module'))
        ) \
        .only(*['answered_at', 'started_at', 'time_given', 'is_correct', 'question_id', 'question__module', 'user_id'])

    # print(get_date_range(timezone.now() - timezone.timedelta(days=DAYS), timezone.now()))
    x_axis = [dt.strftime('%Y-%m-%d') for dt in get_date_range(timezone.now() - timezone.timedelta(days=DAYS - 1), timezone.now())]
    answer_data = {
        'x_axis': x_axis,
        'all': {
            0: [0] * DAYS,
            1: [0] * DAYS,
        },
        Module.MATH.value: {
            0: [0] * DAYS,
            1: [0] * DAYS,
        },
        Module.ENGLISH.value: {
            0: [0] * DAYS,
            1: [0] * DAYS,
        },
    }

    answer_data_unique = {
        'x_axis': x_axis,
        'all': {
            0: [0] * DAYS,
            1: [0] * DAYS,
        },
        Module.MATH.value: {
            0: [0] * DAYS,
            1: [0] * DAYS,
        },
        Module.ENGLISH.value: {
            0: [0] * DAYS,
            1: [0] * DAYS,
        },
    }
    answer_data_unique_questions_by_day = {
        0: [set() for n in range(DAYS)],
        1: [set() for n in range(DAYS)],
    }

    # print('answer_data_unique_questions_by_day', answer_data_unique_questions_by_day)
    # print(len(answer_data_unique_questions_by_day[0]))

    time_given_data = {
        'x_axis': x_axis,
        'all':  [0] * DAYS,
        Module.MATH.value: [0] * DAYS,
        Module.ENGLISH.value: [0] * DAYS,
    }

    for answer in answer_set:
        dts = answer.answered_at.strftime('%Y-%m-%d')
        index = x_axis.index(dts)
        answer_data['all'][answer.is_correct][index] += 1
        answer_data[answer.question.module][answer.is_correct][index] += 1

        if answer.question_id not in answer_data_unique_questions_by_day[answer.is_correct][index]:
            answer_data_unique['all'][answer.is_correct][index] += 1
            answer_data_unique[answer.question.module][answer.is_correct][index] += 1
            answer_data_unique_questions_by_day[answer.is_correct][index].add(answer.question_id)

        # if answer.time_given:
        #     time_given_data['all'][index] += min(answer.time_given.total_seconds(), MAX_TIME_GIVEN_LIMIT)
        #     time_given_data[answer.question.module][index] += min(answer.time_given.total_seconds(), MAX_TIME_GIVEN_LIMIT)

    # print('answer_data_unique', answer_data_unique)
    # print('answer_data_unique_questions_by_day', answer_data_unique_questions_by_day)

    # ----------------------------------------------------------------

    f = lambda: {'items': [], 'corrected': False, 'attempts': 0}
    answers_groups: List = [f()]
    for answer in answer_set:
        if answers_groups[-1]['corrected']:
            answers_groups.append(f())

        if answer.is_correct:
            answers_groups[-1]['items'].append(answer)
            answers_groups[-1]['corrected'] = True
        else:
            answers_groups[-1]['items'].append(answer)
            answers_groups[-1]['attempts'] += 1

    answers_groups.reverse()

    # print('answers_groups', answers_groups)
    for group in answers_groups:
        if not group['items']:
            continue
        group['items'].reverse()
        first_answer = group['items'][0]
        index = x_axis.index(first_answer.answered_at.strftime('%Y-%m-%d'))
        if group['corrected']:
            time_given_data['all'][index] += min(first_answer.time_given.total_seconds(), MAX_TIME_GIVEN_LIMIT)
            time_given_data[first_answer.question.module][index] += min(first_answer.time_given.total_seconds(), MAX_TIME_GIVEN_LIMIT)
        else:
            time_given_data['all'][index] += min(first_answer.time_given.total_seconds(), MAX_TIME_GIVEN_LIMIT)
            time_given_data[first_answer.question.module][index] += min(first_answer.time_given.total_seconds(), MAX_TIME_GIVEN_LIMIT)

    # ----------------------------------------------------------------

    status_set = user \
        .question_status_set \
        .filter(Q(marked_for_review_at__date__gt=date__gte) | Q(unmarked_for_review_at__date__gt=date__gte)) \
        .prefetch_related(
            Prefetch('question', queryset=Question.objects.only('module'))
        ) \
        .only(*['is_marked_for_review', 'marked_for_review_at', 'unmarked_for_review_at', 'question__module', 'user_id'])

    mark_data = {
        'x_axis': x_axis,
        'all': {
            0: [0] * DAYS,
            1: [0] * DAYS,
        },
        Module.MATH.value: {
            0: [0] * DAYS,
            1: [0] * DAYS,
        },
        Module.ENGLISH.value: {
            0: [0] * DAYS,
            1: [0] * DAYS,
        },
    }

    for status in status_set:
        dt = ""
        if status.is_marked_for_review:
            dt = status.marked_for_review_at
        else:
            dt = status.unmarked_for_review_at
        if dt:
            dts = dt.strftime('%Y-%m-%d')
            x_index = x_axis.index(dts)
            if mark_data[status.question.module][status.is_marked_for_review][x_index] is None:
                mark_data[status.question.module][status.is_marked_for_review][x_index] = 0

            mark_data['all'][status.is_marked_for_review][x_index] += 1
            mark_data[status.question.module][status.is_marked_for_review][x_index] += 1

    # print('answer_data', answer_data)
    # print('answer_data_unique', answer_data_unique)

    return render(request, 'basic/pages/charts/index.html', context={
        'current_user': user,
        'answer_data': answer_data,
        'answer_data_unique': answer_data_unique,
        'mark_data': mark_data,
        'time_given_data': time_given_data,
    })


@login_required
def basic_exam_time_view(request, exam_id, user_id=None, username=None):
    exam = get_object_or_404(
        Exam.objects.prefetch_related(
            Prefetch('exam_question_set', queryset=ExamQuestion.objects.order_by('order')),
            Prefetch('exam_question_set__question', queryset=Question.objects.only(*['module']))),
        id=exam_id
    )

    user: Optional[User] = None
    if not user_id and not username:
        user = request.user
    else:
        if user_id:
            user = get_object_or_404(User, id=user_id)
        elif username:
            user = get_object_or_404(User, username=username)

    if not user:
        raise Http404

    ctx = {}

    exam_questions_answers = UserQuestionAnswer.objects \
        .filter(user_id=user.id, question_id__in=exam.exam_question_set.values_list('question_id', flat=True)) \
        .only(*['time_given', 'is_correct', 'started_at', 'answered_at', 'question_id', 'user_id']).order_by('-answered_at')

    exam_questions_status = UserQuestionStatus.objects \
        .filter(user_id=user.id, question_id__in=exam.exam_question_set.values_list('question_id', flat=True)) \
        .only(*['is_marked_for_review', 'marked_for_review_at', 'unmarked_for_review_at', 'question_id', 'user_id'])

    exam_questions_set = exam.exam_question_set.all()

    questions_order_to_id = {question.order: question.question_id for question in exam_questions_set}
    # k -> question_id, v -> dict
    questions_data = defaultdict(lambda: {
        'correct_count': 0, 'correct_times': [], 'correct_time_avg': 0,
        'incorrect_count': 0, 'incorrect_times': [], 'incorrect_time_avg': 0,
        'attempted_count': 0, 'attempted_times': [], 'attempted_time_avg': 0,
        'time': 0, 'answers': OrderedDict(), 'status': None
    })

    for question_answer in exam_questions_answers:
        questions_data[question_answer.question_id]['answers'][question_answer.id] = question_answer

        for k in (['correct'] if question_answer.is_correct else ['incorrect']) + ['attempted']:
            questions_data[question_answer.question_id][f'{k}_times'].append(question_answer.time_given.total_seconds())
            questions_data[question_answer.question_id][f'{k}_count'] += 1

    for question_status in exam_questions_status:
        questions_data[question_status.question_id]['status'] = question_status

    for q_id in questions_data.keys():
        question_data = questions_data[q_id]
        question_data['correct_time_avg'] = sum(question_data['correct_times']) / question_data['correct_count'] if question_data['correct_count'] else 0

templates/basic/pages/charts/admin.html
{% extends "basic/pages/charts/base.html" %}
{% load core_tags static %}

{% block title %}Admin Chart - {{ block.super }}{% endblock %}

{% block content %}
    {% if kpi %}
        <div class="stats">
            {% for stats in kpi %}
                <div class="stat">
                    <div class="stat-title">{{ stats.title }}</div>
                    <div class="stat-value">{{ stats.metric }}</div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <div>
        <h2 class="text-3xl font-bold">
            New users in last {{ days }} days
        </h2>
        <div id="users-chart" style="max-height: 300px;"></div>
            <script>
                let chart = new Highcharts.Chart({
                    chart: {
                        renderTo: 'users-chart',
                        backgroundColor: 'transparent'
                    },
                    title: {text: '', style: {display: 'none'}},
                    subtitle: {text: '', style: {display: 'none'}},
                    xAxis: {
                        categories: {{ chart_users_data.axis | jsonify }},
                    },
                    yAxis: {
                        title: {
                            text: 'Registrations'
                        }
                    },
                    series: [{
                        name: 'Users',
                        data: {{ chart_users_data.values | jsonify }},
                    }],
                    legend:{enabled:false},
                    credits: {enabled: false},
                });
            </script>
    </div>

    <div>
        <h2 class="text-3xl font-bold">
            New attempts in last {{ days }} days
        </h2>
        <div id="attempts-chart" style="max-height: 400px;"></div>
        <h3 class="text-xl font-bold">English</h3>
        <div id="english-attempts-chart" style="max-height: 400px;"></div>
        <h3 class="text-xl font-bold">Math</h3>
        <div id="math-attempts-chart" style="max-height: 400px;"></div>
            <script>
                let chart_attempts_base = {
                    tooltip: {
                        shared: true,
                        split: false,
                        enabled: true
                    },
                    xAxis: {
                        categories: {{ chart_attempts_data.axis | jsonify }},
                    },
                    title: {text: '', style: {display: 'none'}},
                    subtitle: {text: '', style: {display: 'none'}},
                    credits: {enabled: false},
                }
                let values = {{ chart_attempts_data | jsonify }};
                let chart_attempts = new Highcharts.Chart({
                    ...chart_attempts_base,
                    chart: {
                        renderTo: 'attempts-chart',
                        backgroundColor: 'transparent'
                    },
                    yAxis: {
                        title: {
                            text: 'Attempts'
                        }
                    },
                    series: [
                        {name: 'Attempts', data: values.all.all},
                        {name: 'Incorrect Attempts', data: values.all.incorrect, color: '#e74c3c'},
                        {name: 'Correct Attempts', data: values.all.correct, color: '#27ae60'},
                        {name: 'Questions Count', data: values.questions.all},
                        {name: 'Users Count', data: values.users.all},
                    ],
                });
                let chart_english_attempts = new Highcharts.Chart({
                    ...chart_attempts_base,
                    chart: {
                        renderTo: 'english-attempts-chart',
                        backgroundColor: 'transparent'
                    },
                    yAxis: {
                        title: {
                            text: 'Attempts (English)'
                        }
                    },
                    series: [
                        {name: 'Attempts', data: values.en.all},
                        {name: 'Incorrect Attempts', data: values.en.incorrect, color: '#e74c3c'},
                        {name: 'Correct Attempts', data: values.en.correct, color: '#27ae60'},
                        {name: 'Questions Count', data: values.questions.en},
                        {name: 'Users Count', data: values.users.en},
                    ],
                });
                let chart_math_attempts = new Highcharts.Chart({
                    ...chart_attempts_base,
                    chart: {
                        renderTo: 'math-attempts-chart',
                        backgroundColor: 'transparent'
                    },
                    yAxis: {
                        title: {
                            text: 'Attempts (Math)'
                        }
                    },
                    series: [
                        {name: 'Attempts', data: values.math.all},
                        {name: 'Incorrect Attempts', data: values.math.incorrect, color: '#e74c3c'},
                        {name: 'Correct Attempts', data: values.math.correct, color: '#27ae60'},
                        {name: 'Questions Count', data: values.questions.math},
                        {name: 'Users Count', data: values.users.math},
                    ],
                });
            </script>
    </div>

{% endblock content %}

templates/basic/pages/charts/base.html
{% extends "basic/base.html" %}
{% load core_tags static %}

{% block javascript %}
    {% if not IS_BLACKOUT %}
        <script src="https://code.highcharts.com/highcharts.js"></script>
    {% else %}
        <script src="{% static 'cdn/highcharts.11.4.6.min.js' %}"></script>
    {% endif %}

    <!-- https://evanhahn.github.io/HumanizeDuration.js/ -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/humanize-duration/3.32.1/humanize-duration.min.js"
            integrity="sha512-IuW3C7hqTl2pnZ+OX+lHFEc8QOYJCVyNSKmRTAmJJ9J0xwru4wYTar2MM80MSbhOiZKmGc+uypnPZKrCVga2xg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    {{ block.super }}
{% endblock %}

templates/basic/pages/charts/exam_chart.html
{% extends "basic/pages/charts/base.html" %}

{% load core_tags static mathfilters %}

{% block title %}{{ exam.name }}'s Charts - {{ block.super }}{% endblock %}

{% block content %}

    <h1 class="text-3xl font-semibold mt-4 mb-2">
        User: <span class="text-primary">{% if current_user.name %}{{ current_user.name }}
        - {% endif %}{{ current_user.username }}</span>
        <div class="badge ">This page may contain unwanted bugs</div>
        <br>
        Practice Test: <span class="text-primary">{{ exam.name }}</span>
    </h1>

    <div class="flex justify-center">
        <div class="stats stats-vertical lg:stats-horizontal">
            <div class="stat place-items-center">
                <div class="stat-title">Total Time for Correct Answers (Min-Max)</div>
                {% if total_correct_time_min == total_correct_time_max %}
                    <div class="stat-value">{{ total_correct_time_max | duration_short }}</div>
                {% else %}
                    <div class="stat-value">{{ total_correct_time_min | duration_short }}
                        - {{ total_correct_time_max | duration_short }}</div>
                {% endif %}
            </div>
            <div class="stat place-items-center">
                <div class="stat-title">Average Time for Correct Answers (Min-Max)</div>
                {% if total_correct_time_min_avg == total_correct_time_max_avg %}
                    <div class="stat-value">{{ total_correct_time_max_avg | duration_short }}</div>
                {% else %}
                    <div class="stat-value">{{ total_correct_time_min_avg | duration_short }}
                        - {{ total_correct_time_max_avg | duration_short }}</div>
                {% endif %}

            </div>
        </div>
    </div>



    <table class="table table-zebra table-xs">
        <thead>
        <tr>
            <th class="text-center">#</th>
            <th></th>
            <th colspan="5">
                Times (Recent to Oldest)
            </th>
        </tr>
        <tr>
            <th colspan="2" class=""></th>
            <th>#1</th>
            <th>#2</th>
            <th>#3</th>
            <th>#4</th>
            <th>#5</th>
        </tr>
        </thead>
        <tbody>
        {% for exam_question in exam_questions_set %}
            <tr>
                <td class="text-center">
                    <a class="hover:underline px-8 btn btn-xs btn-outline underline" target="_blank"
                       href="{% url 'questions:detail' exam_question.question_id %}?question_set=exam&exam_id={{ exam.id }}">
                        {{ forloop.counter }}
                    </a>
                </td>
                {% with question_data=questions_data|get_item:exam_question.question_id %}
                    <td class="">
                        {% if question_data.correct_count %}
                            <div class="badge badge-sm badge-success">
                                {{ question_data.correct_count }}
                            </div>
                        {% endif %}
                        {% if question_data.incorrect_count %}
                            <div class="badge badge-sm badge-error badge-outline text-error-content">
                                {{ question_data.incorrect_count }}
                            </div>
                        {% endif %}
                        {% if question_data.status and question_data.status.is_marked_for_review %}
                             <span class="badge badge-outline badge-warning badge-sm text-warning-content">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="text-warning" style="width: 0.65rem; height: 0.65rem;"><path fill-rule="evenodd" d="M6.32 2.577a49.255 49.255 0 0 1 11.36 0c1.497.174 2.57 1.46 2.57 2.93V21a.75.75 0 0 1-1.085.67L12 18.089l-7.165 3.583A.75.75 0 0 1 3.75 21V5.507c0-1.47 1.073-2.756 2.57-2.93Z" clip-rule="evenodd" /></svg>
                             </span>
                        {% endif %}
                    </td>

                    {% for correct_time in question_data.correct_times|slice:":5" %}
                        <td class="">{{ correct_time | duration }}</td>
                    {% endfor %}

                    {% with correct_times_length=question_data.correct_times|length %}
                        {% with missing=5|sub:correct_times_length %}
                            {% if missing > 0 %}
                            	{% for n in missing|range %}
                                    <td class=""></td>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                    {% endwith %}
                {% endwith %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="border-2 bg-base-200 rounded p-3 mb-4">
        <h2 class="text-2xl text-center mb-3 font-semibold">
            Correct Time Spent
        </h2>

        <div id="correct-times-chart-container"></div>
    </div>
{% endblock %}

{% block inline_javascript %}
    {{ block.super }}

    <script>
        let base_chart_data = {
            tooltip: {
                shared: true,
                split: false,
                enabled: true,
            },
        }

        function correct_times_chart(correct_times_data) {
            let id = 'correct-times-chart-container';

            let titles = {
                'correct_times_min': 'Min',
                'correct_times_max': 'Max',
                'correct_times_avg': 'Avg',
            }

            console.log(correct_times_data)

            let series = [];
            for (let k of ['correct_times_min', 'correct_times_max', 'correct_times_avg']) {
                if (k != 'correct_times_avg') {
                    if (JSON.stringify(correct_times_data[k]) == JSON.stringify(correct_times_data['correct_times_avg'])) {
                        continue;
                    }
                }

                series.push({
                    name: titles[k],
                    data: correct_times_data[k],
                    dataLabels: {
                        enabled: true,
                        formatter: function () {
                            let s = humanizeDuration(this.y * 1000);
                            s = s.replace(' days', 'd ').replace(' hours', 'h ').replace(' minutes', 'm ').replace(' seconds', 's ');
                            s = s.replace(' day', 'd ').replace(' hour', 'h ').replace(' minute', 'm ').replace(' second', 's ');
                            s = s.replaceAll(', ', '');
                            return s.trimEnd();
                        }
                    }
                });
            }

            console.log(series)

            let chart_data = {
                ...base_chart_data,
                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                        enableMouseTracking: true
                    }
                },
                title: {
                    text: 'Correct Times',
                    align: 'left'
                },
                xAxis: {
                    categories: correct_times_data.x_axis,
                    title: {
                        text: 'Correct Times'
                    }
                },
                yAxis: {
                    title: {
                        text: 'Time Spent'
                    }
                },
                series: series
            }

            // humanizeDuration
            // https://jsfiddle.net/BlackLabel/6hy15Lp3/
            // https://stackoverflow.com/a/19315076/4854605
            chart_data.tooltip.formatter = function () {
                let s = [];

                this.points.forEach(function (point, i) {
                    s.push(`<span style="color:${point.series.color}; font-weight:bold;">${point.series.name}: ${humanizeDuration(point.y * 1000)}<span>`);
                });

                return `${this.x}: Correct Times <br/>` + s.join('<br/><br/>');
            }

            Highcharts.chart(id, chart_data);
        }

        correct_times_chart({{ correct_times_data|jsonify }});
    </script>
{% endblock %}