api/urls.py
from django.contrib import admin
from django.urls import path
from ninja import NinjaAPI

from questions.api.api_v1 import router as questions_router
from users.api.api_v1 import router as users_router

from ninja import NinjaAPI

# app_name = 'api'

api_v1 = NinjaAPI(version='1.0.0', urls_namespace='api_v1')


# @api.get('/hello')
# def hello(request):
#     return {'message': 'Hello from V1'}
#
#
# @api.get("/add")
# def add(request, a: int, b: int):
#     return {"result": a + b}


api_v1.add_router("/questions/", questions_router)
api_v1.add_router("/users/", users_router)
# Exam

urlpatterns = [
    path('v1/', api_v1.urls, name='api_v1'),
]

charts/urls.py
from django.urls import path

from . import views

app_name = 'charts'

urlpatterns = [
    # path("user/<int:user_id>/charts/", views.chart_view, name="chart_with_user_id"),
    path("user/<str:username>/charts/", views.chart_view, name="chart_with_username"),
    path("user/charts/", views.chart_view, name="chart"),

    path('charts/admin/', views.admin_chart_view, name="admin_chart"),


    # path("charts/user/<int:user_id>/exam/<int:exam_id>/basic-time", views.basic_exam_time_view),
    path("charts/user/<str:username>/exam/<int:exam_id>/basic-time", views.basic_exam_time_view),
    path("charts/user/exam/<int:exam_id>/basic-time", views.basic_exam_time_view, name="basic_exam_time"),


]

exams/urls.py
from django.urls import path

from . import views

app_name = 'exams'

urlpatterns = [
    path('exams/', views.ExamListView.as_view(), name='list'),
]

questions/urls.py
from django.urls import path
from . import views


app_name = 'questions'
urlpatterns = [
    path('question-set/first-question/', views.question_set_first_question_view, name='set-first-question'),

    path('question-set/college-board-question-bank/', views.CollegeBoardQuestionBankCategoryListView.as_view(), name='question-set-cbqb'),
    path('question-set/princeton-review-practice-tests-question-bank/', views.PrincetonReviewPracticeTestsQuestionBankCategoryListView.as_view(), name='question-set-prptqb'),
    path('question-set/<str:question_set>/', views.QuestionSetView.as_view(), name='question-set'),
    # first question
    # path('questions/', views.QuestionListView.as_view(), name='question_list'),
    #
    path('question/<int:pk>/', views.QuestionDetailView.as_view(), name='detail'),
]

users/urls.py
from django.urls import path

from users.views import user_detail_view
from users.views import user_redirect_view
from users.views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

templates/basic/components/donation_notice_progress.html
{% if DONATION_TARGET %}
    <div class="flex items-center space-x-3 mt-2 px-4">
        <span>Target:</span>
        <span class="font-bold">{{ DONATION_AMOUNT }}$</span>
        <progress class="progress progress-success w-full" value="{{ DONATION_AMOUNT }}"
                  max="{{ DONATION_TARGET }}"></progress>
        <span class="font-bold">{{ DONATION_TARGET }}$</span>
    </div>
{% endif %}

templates/basic/components/google_analytics.html
<!-- Google tag (gtag.js) -->
{% if GOOGLE_ANALYTICS_ID %}
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS_ID }}"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', '{{ GOOGLE_ANALYTICS_ID }}', {
            {% if request.user.is_authenticated %}
                'user_id': '{{ request.user.id }}',
            {% endif %}
        });
    </script>
{% endif %} 

templates/basic/components/nav-links.html
<li>
    <a href="{% url 'home' %}">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
             style="width: 1.25rem;" class="text-primary">
            <path stroke-linecap="round" stroke-linejoin="round"
                  d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25"/>
        </svg>
        Home
    </a>
</li>
<li>
    <a href="{% url 'exams:list' %}">
        <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
             style="width: 1.25rem;" class="text-primary">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M15 4h3a1 1 0 0 1 1 1v15a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h3m0 3h6m-6 5h6m-6 4h6M10 3v4h4V3h-4Z"/>
        </svg>
        Practice Tests
    </a>
</li>
<li>
    {% if not mobile %}
        <details>
        <summary>Question Sets</summary>
    {% else %}
        <a>Question Sets</a>
    {% endif %}

    <ul class="p-2 lg:w-[18rem]">
        <li>
            <a href="{% url 'questions:question-set-cbqb' %}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                    <path fill-rule="evenodd"
                          d="M9 4.5a.75.75 0 0 1 .721.544l.813 2.846a3.75 3.75 0 0 0 2.576 2.576l2.846.813a.75.75 0 0 1 0 1.442l-2.846.813a3.75 3.75 0 0 0-2.576 2.576l-.813 2.846a.75.75 0 0 1-1.442 0l-.813-2.846a3.75 3.75 0 0 0-2.576-2.576l-2.846-.813a.75.75 0 0 1 0-1.442l2.846-.813A3.75 3.75 0 0 0 7.466 7.89l.813-2.846A.75.75 0 0 1 9 4.5ZM18 1.5a.75.75 0 0 1 .728.568l.258 1.036c.236.94.97 1.674 1.91 1.91l1.036.258a.75.75 0 0 1 0 1.456l-1.036.258c-.94.236-1.674.97-1.91 1.91l-.258 1.036a.75.75 0 0 1-1.456 0l-.258-1.036a2.625 2.625 0 0 0-1.91-1.91l-1.036-.258a.75.75 0 0 1 0-1.456l1.036-.258a2.625 2.625 0 0 0 1.91-1.91l.258-1.036A.75.75 0 0 1 18 1.5ZM16.5 15a.75.75 0 0 1 .712.513l.394 1.183c.15.447.5.799.948.948l1.183.395a.75.75 0 0 1 0 1.422l-1.183.395c-.447.15-.799.5-.948.948l-.395 1.183a.75.75 0 0 1-1.422 0l-.395-1.183a1.5 1.5 0 0 0-.948-.948l-1.183-.395a.75.75 0 0 1 0-1.422l1.183-.395c.447-.15.799-.5.948-.948l.395-1.183A.75.75 0 0 1 16.5 15Z"
                          clip-rule="evenodd"/>
                </svg>
                College Board Question Bank
            </a>
            <a href="{% url 'questions:question-set-prptqb' %}">
                The Princeton Review Practice Tests Question Bank
            </a>
        </li>
    </ul>

    {% if not mobile %}
        </details>
    {% endif %}
</li>
<li>
    <a href="{% url 'charts:chart' %}">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
             style="width: 1.25rem;" class="text-primary">
            <path stroke-linecap="round" stroke-linejoin="round"
                  d="M7.5 14.25v2.25m3-4.5v4.5m3-6.75v6.75m3-9v9M6 20.25h12A2.25 2.25 0 0 0 20.25 18V6A2.25 2.25 0 0 0 18 3.75H6A2.25 2.25 0 0 0 3.75 6v12A2.25 2.25 0 0 0 6 20.25Z"/>
        </svg>
        Charts
    </a>
</li>

<li class="{% if COUNTRY_CODE != 'BD' %}dont-hide{% endif %}">
    <a href="{% url 'donate' %}">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
            style="width: 1.25rem;" class="text-success">
            <path stroke-linecap="round" stroke-linejoin="round"
                  d="M12 6v12m-3-2.818.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
        </svg>
        Donate
    </a>
</li>

<li>
    <a href="{% url 'about' %}">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
             style="width: 1.25rem;" class="text-primary">
            <path stroke-linecap="round" stroke-linejoin="round"
                  d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z"/>
        </svg>
        About
    </a>
</li>

templates/basic/components/nav.html
<div class="navbar bg-base-300 z-[100]">
    <div class="navbar-start">
        <div class="dropdown">
            <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                     stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16"/>
                </svg>
            </div>
            <ul tabindex="0" class="menu menu dropdown-content mt-3 z-[100] p-2 shadow bg-base-200 rounded-box w-64">
                {% include "basic/components/nav-links.html" with mobile=1 %}
            </ul>
        </div>
        <a class="btn btn-ghost text-xl" href="/">OnePrep</a>
    </div>
    <div class="navbar-center hidden lg:flex">
        <ul class="menu menu-horizontal px-1 z-[100]">
            {% include "basic/components/nav-links.html" %}
        </ul>
    </div>
    <div class="navbar-end">
        {% if request.user.is_authenticated %}
        <div class="dropdown dropdown-end">
            <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
                <div class="w-10 rounded-full text-primary">
{#                    <img alt="Tailwind CSS Navbar component" src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg"/>#}
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-10"><path fill-rule="evenodd" d="M18.685 19.097A9.723 9.723 0 0 0 21.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 0 0 3.065 7.097A9.716 9.716 0 0 0 12 21.75a9.716 9.716 0 0 0 6.685-2.653Zm-12.54-1.285A7.486 7.486 0 0 1 12 15a7.486 7.486 0 0 1 5.855 2.812A8.224 8.224 0 0 1 12 20.25a8.224 8.224 0 0 1-5.855-2.438ZM15.75 9a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" clip-rule="evenodd" /></svg>
                </div>
            </div>
            <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
                <li class="menu-title">{{ request.user.username }}</li>
                <li>
                    <a class="justify-between" href="{% url 'users:detail' request.user.pk %}">
                        Profile
{#                        <span class="badge">New</span>#}
                    </a>
                </li>
{#                <li><a>Settings</a></li>#}
                {% if request.user.is_staff %}
                	<li>
                        <a href="{% url 'admin:index' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4"><path fill-rule="evenodd" d="M12 6.75a5.25 5.25 0 0 1 6.775-5.025.75.75 0 0 1 .313 1.248l-3.32 3.319c.063.475.276.934.641 1.299.365.365.824.578 1.3.64l3.318-3.319a.75.75 0 0 1 1.248.313 5.25 5.25 0 0 1-5.472 6.756c-1.018-.086-1.87.1-2.309.634L7.344 21.3A3.298 3.298 0 1 1 2.7 16.657l8.684-7.151c.533-.44.72-1.291.634-2.309A5.342 5.342 0 0 1 12 6.75ZM4.117 19.125a.75.75 0 0 1 .75-.75h.008a.75.75 0 0 1 .75.75v.008a.75.75 0 0 1-.75.75h-.008a.75.75 0 0 1-.75-.75v-.008Z" clip-rule="evenodd" /><path d="m10.076 8.64-2.201-2.2V4.874a.75.75 0 0 0-.364-.643l-3.75-2.25a.75.75 0 0 0-.916.113l-.75.75a.75.75 0 0 0-.113.916l2.25 3.75a.75.75 0 0 0 .643.364h1.564l2.062 2.062 1.575-1.297Z" /><path fill-rule="evenodd" d="m12.556 17.329 4.183 4.182a3.375 3.375 0 0 0 4.773-4.773l-3.306-3.305a6.803 6.803 0 0 1-1.53.043c-.394-.034-.682-.006-.867.042a.589.589 0 0 0-.167.063l-3.086 3.748Zm3.414-1.36a.75.75 0 0 1 1.06 0l1.875 1.876a.75.75 0 1 1-1.06 1.06L15.97 17.03a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" /></svg>
                            Admin
                        </a>
                    </li>
                {% endif %}
                <li>
                    <a href="{% url 'account_logout' %}">Logout</a>
                </li>
            </ul>
        </div>
        {% else %}
            {% if ACCOUNT_ALLOW_REGISTRATION %}
                <a href="{% url 'account_signup' %}" class="btn btn-secondary mr-2">Register</a>
            {% endif %}
            <a href="{% url 'account_login' %}" class="btn btn-primary">Login</a>
        {% endif %}
    </div>
</div>